produtos/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, patterns, include
from django.contrib import admin

from produtos.views import ( abre_importa_planilha, abre_contagem_estoque_rotativo, carregar_produtos,
        abre_analitico_contagem_estoque_rotativo, abre_entrada_manual_estoque, buscar_produto_estoque,
        salvar_estoquediario, atualizar_produtos_classes  )
from produtos.ferramentas import eliminar_produtos_duplicados

urlpatterns = [
    url(r'^contagem-estoque-rotativo/$', abre_contagem_estoque_rotativo),
    url(r'^analitico-contagem-estoque-rotativo/$', abre_analitico_contagem_estoque_rotativo),
    url(r'^importar-planilha/$', abre_importa_planilha),
    url(r'^entrada-manual-estoque/$', abre_entrada_manual_estoque),
    url(r'^carregar-produtos/$', carregar_produtos),
    url(r'^buscar-produto-estoque/$', buscar_produto_estoque),
    url(r'^salvar-estoquediario/$', salvar_estoquediario),
    url(r'^atualizar-produtos-classes/$', atualizar_produtos_classes),

    # Ferramentas
    url(r'^eliminar-produtos-duplicados/$', eliminar_produtos_duplicados),
]

sistema/urls.py
# -*- coding: utf-8 -*-

from django.urls import path, include

from django.contrib import admin
from django.conf import settings
from django.contrib.auth import views

from sistema.views import home, alerta_email_entrada_dados, abre_index_adm
from sistema.ferramentas import cria_novos_produtos_de_clientes


urlpatterns = [
    path('admin/', admin.site.urls),
    path('painel/', abre_index_adm),
    path('logout/', views.logout, {'next_page': settings.LOGOUT_REDIRECT_URL},),
    path("", home),
    path('produtos/', include('produtos.urls')),
    path('clientes/', include('clientes.urls')),
    path('inventario/', include('inventario.urls')),
    path('sistema/alerta-email-entrada-dados/', alerta_email_entrada_dados),
    path('sistema/cria-novos-produtos-de-clientes/', cria_novos_produtos_de_clientes),
]

from django.conf import settings

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

produtos/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import datetime  #, re
from django.db import models
from django.db.models import signals
from django.template.defaultfilters import slugify
from xlrd import open_workbook, xldate_as_tuple

from clientes.models import Cliente, Conferente, Funcionario
from produtos.choices import MESES
from uteis.funcoes import leitor_planilha_modelo1
from produtos.choices import OPCAODUPLICADOS_CHOICES, OPCAODUPLICADOS_SOMAR, OPCAODUPLICADOS_SUBSTITUIR


class ProdutoClasse(models.Model):
    """
    Armazena as Classes dos Produtos.
    """

    cliente = models.ForeignKey(Cliente, related_name='produtosclasse_do_cliente', blank=True, null=True, on_delete=models.PROTECT)
    nome    = models.CharField(max_length=40)
        
    class Meta:
        ordering = ('nome',)
        verbose_name = 'Classe'
        verbose_name_plural = 'Classes'

    def __unicode__(self):
        return self.nome


class Produto(models.Model):
    """
    Armazena os Produtos dos Clientes.
    """

    classe         = models.ForeignKey(ProdutoClasse, related_name='produtos_da_classe', blank=True, null=True, on_delete=models.PROTECT)
    cliente        = models.ForeignKey(Cliente, related_name='produtos_de_cliente', blank=True, null=True, on_delete=models.CASCADE)
    codigo_barras  = models.CharField(max_length=20, db_index=True,)
    codigo_interno = models.IntegerField(default=0, blank=True, null=True, db_index=True)
    descricao      = models.CharField(verbose_name=u'Descrição', max_length=80)
    slug           = models.SlugField(blank=True, null=True, max_length=80)
    embalagem      = models.IntegerField(default=1, blank=True, null=True, 
            help_text=u'Quantidade de produtos por embalagem. Exemplo: "10" quer dizer que na embalagem tem 10 pacotes do produto.')
    custo_unitario = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, blank=True, null=True)
        
    class Meta:
        ordering = ('descricao',)
        verbose_name = 'Produto'
        verbose_name_plural = 'Produtos'
        permissions = (
                ('importar_planilha', u'Pode Importar Planilha Excel'),
                ('gerar_pdf_contagem_totativo', u'Gerar PDF Contagem Estoque Rotativo'),
                ('gerar_pdf_analitico_contagem_totativo', u'Gerar PDF Analítico Contagem Estoque Rotativo'),
                ('adicionar_estoque_manualmente', u'Pode Adicionar Estoque Manualmente'),
                ('enviar_email_alerta_cliente_sem_estoque', u'Pode Enviar Email Alerta a Clientes sem Estoque'),
                )

    def __unicode__(self):
        return u'%s'%(self.descricao)


class EstoqueDiarioManager(models.Manager):
    def importar_arquivo(self, arquivo, cliente_nome, conferente_nome, data, opcao_duplicados):

        ret = leitor_planilha_modelo1( arquivo )
        res         = ret['res']
        campos      = ret['campos']
        nota        = ret['nota']
        lista_erros = ret['lista_erros']

        msg = u'Arquivo importado com sucesso!'

        if campos:

            # Obtem o cliente
            cliente = Cliente.objects.get(fantasia=cliente_nome)
            # Obtem o conferente
            conferente = Conferente.objects.get(nome=conferente_nome)

            for c in campos:

                # Se tiver erro no registro ------------------------
                if c['erro']:
                    continue
                # --------------------------------------------------

                # Verificar se o produto já foi cadastrado (atualizar ou cadastrar)
                produto, new = Produto.objects.get_or_create(
                    cliente        = cliente, 
                    codigo_interno = c['p_codigo'],
                    codigo_barras  = c['p_codigo_barras']
                )

                if new:
                    produto.codigo_interno = c['p_codigo']
                    produto.descricao = c['p_descricao']
                    produto.embalagem = c['p_embalagem']
                    produto.custo_unitario = c['p_custo_unitario']
                    produto.save()
                else:
                    if not produto.custo_unitario == c['p_custo_unitario']:
                        produto.custo_unitario = c['p_custo_unitario']
                        produto.save()
                    if not produto.descricao:
                        produto.descricao
                        produto.save()
                    if produto.codigo_interno == 0 and not c['p_codigo'] == 0:
                        produto.codigo_interno = c['p_codigo']
                        produto.save()
                # --------------------------------------------

                # Criar ou Atualiza registro no Estoque Diário ------------
                try:
                    est = self.get(produto=produto, data=data)
                    est.conferente = conferente
                    
                    if opcao_duplicados == OPCAODUPLICADOS_SOMAR: # Somar duplicados
                        est.estoque_fisico_gondola += c['p_gondola']
                        est.estoque_fisico_deposito += c['p_deposito']
                        est.estoque_fisico_avaria += c['p_avaria']
                        est.estoque_fisico_producao += c['p_producao']
                        est.estoque_fisico_lanche += c['p_lanche']
                        est.estoque_fisico_outros += c['p_outros']
                        est.estoque_sistema += c['p_sistema']
                    elif opcao_duplicados == OPCAODUPLICADOS_SUBSTITUIR: # Substituir duplicados
                        est.estoque_fisico_gondola = c['p_gondola']
                        est.estoque_fisico_deposito = c['p_deposito']
                        est.estoque_fisico_avaria = c['p_avaria']
                        est.estoque_fisico_producao = c['p_producao']
                        est.estoque_fisico_lanche = c['p_lanche']
                        est.estoque_fisico_outros = c['p_outros']
                        est.estoque_sistema = c['p_sistema']
                        
                    est.custo_unitario = c['p_custo_unitario']
                    est.save()
                except EstoqueDiario.DoesNotExist:
                    self.create(
                        produto                 = produto,
                        conferente              = conferente,
                        data                    = data,
                        estoque_fisico_gondola  = c['p_gondola'],
                        estoque_fisico_deposito = c['p_deposito'],
                        estoque_fisico_avaria   = c['p_avaria'],
                        estoque_fisico_producao = c['p_producao'],
                        estoque_fisico_lanche   = c['p_lanche'],
                        estoque_fisico_outros   = c['p_outros'],
                        estoque_sistema         = c['p_sistema'],
                        custo_unitario          = c['p_custo_unitario'],
                    )
                # ----------------------------------------------

        else: # Caso não encontre nenhuma aba com o padrão esperado
            msg = u'Essa planilha está fora do padrão! Verifique o cabeçalho da planilha se está idêntico ao padrão e tente novamente.'
        
        ret = None

        return msg


class EstoqueDiario(models.Model):
    """
    Armazena o Estoque Diário dos Produtos.
    """

    produto                 = models.ForeignKey(Produto, related_name='produtos_do_estoque', blank=True, null=True, on_delete=models.PROTECT)
    #conferente              = models.ForeignKey(Conferente, blank=True, null=True, related_name='estoques_do_conferente')
    conferente              = models.ForeignKey(Funcionario, blank=True, null=True, related_name='estoques_do_conferente', on_delete=models.PROTECT)
    data                    = models.DateField(default=datetime.date.today)
    estoque_fisico_gondola  = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, blank=True, null=True)
    estoque_fisico_deposito = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, blank=True, null=True)
    estoque_fisico_avaria   = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, blank=True, null=True)
    estoque_fisico_producao = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, blank=True, null=True)
    estoque_fisico_lanche   = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, blank=True, null=True)
    estoque_fisico_outros   = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, blank=True, null=True)
    estoque_fisico_total    = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, blank=True, null=True)
    estoque_sistema         = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, blank=True, null=True)
    diferenca               = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, blank=True, null=True)
    custo_unitario = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, blank=True, null=True)
    custo_total    = models.DecimalField(default=0.00, max_digits=12, decimal_places=2, blank=True, null=True)

    dia    = models.CharField(max_length=2, blank=True, null=True)
    mes    = models.CharField(max_length=2, choices=MESES, blank=True, null=True) 
    ano    = models.CharField(max_length=4, blank=True, null=True)
    semana = models.CharField(max_length=2, blank=True, null=True)
    
    # Campos relacionados com a importação de estoque do sistema ------------------------
    opcao_duplicados = models.CharField(verbose_name=u'Opção produtos duplicados', max_length=1, default='1',
            choices=OPCAODUPLICADOS_CHOICES,
            help_text=u'O que o sistema deve fazer quando encontrar um produto que já foi importado: "Ignorar", "Somar" ou "Substituir"?')
    erros_importacao = models.TextField(verbose_name=u'Erros na importação', blank=True, null=True, default='',

produtos/templates/analitico-contagem-estoque-rotativo.html
{% extends "admin/base_site.html" %}


{% block content %}{{ block.super }}

<h1>Relatório <small>Contagem Estoque Rotativo por Grupo</small></h1>

<form method="POST" enctype="multipart/form-data">{% csrf_token %}
    <div class="inner">
        <table class="form">
            {{form}}
        </table>
    </div>
	<br />
    <button type="submit">Gerar PDF</button>
</form>

<br/>

<p><small>Explicar sobre o relatório.</small></p>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script type="text/javascript" src="{{ STATIC_URL }}admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/zepto.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.mask.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/relatorio-analitico-contagem-estoque.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

{% endblock %}

produtos/templates/contagem-estoque-rotativo.html
{% extends "admin/base_site.html" %}

{% block content %}{{ block.super }}

<h1>Relatório <small>Contagem Estoque Rotativo por Produto</small></h1>
<form method="POST" enctype="multipart/form-data">{% csrf_token %}
	<!-- [08/08/19] Modified by: R.Zacche 
    <div class="inner"> -->
    <div class="inner" ng-app="appPilar" ng-controller="ctrlContagemEstoqueRotativo">
        <table class="form">
            {{form}}
			<!-- [08/08/19] Added by: R.Zacche - INI -->
			<style>
			.btn-primary {
				color: #fff;
				background-color: #007bff;
				border-color: #007bff;
			}
			.btn {
				display: inline-block;
				font-weight: 400;
				text-align: center;
				white-space: nowrap;
				vertical-align: middle;
				-webkit-user-select: none;
				-moz-user-select: none;
				-ms-user-select: none;
				user-select: none;
				border: 1px solid transparent;
				padding: .105rem .5rem;
				font-size: 1rem;
				line-height: 1.5;
				border-radius: .25rem;
				transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out,box-shadow .15s ease-in-out;
			}
			.alert-primary {
				color: #004085;
				background-color: #cce5ff;
				border-color: #b8daff;
			}
			.alert {
				position: relative;
				padding: .75rem 1.25rem;
				margin-top: .3rem;
				border: 1px solid transparent;
				border-radius: .25rem;
			}
			</style>
			<tr>
				<td colspan="2">
					<b>Códigos ou descrição:</b>
					<div class="input-group">						
						<input class="form-control" type="search" id="textoBusca">
						<span class="input-group-append">
							<!-- O elemento abaixo só é visivel em mobile. Oculto em tablets e computador -->
							<button ng-click="buscarProduto()" class="btn btn-primary" type="button" id="buscarProduto">
								Pesquisar
							</button>
						</span>
						<div ng-if="produtos">
							<!--<div ng-bind="produto.label" class="alert alert-primary">
							</div>-->
							<input type="hidden" name="produto_pk" id="produto_pk" />
							<table id="listaProdutos" style="margin-top:8px">
								<thead>
									<tr>
										<th>Produto</th>
										<th></th>
									</tr>
								</thead>
								<tbody>
									<tr ng-repeat="prod in produtos">
										<td><input type="radio" name="prod" ng-click="selecionarProduto()" /></td>
										<td ng-bind="prod.label"></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</td>
			</tr>
			<!-- [08/08/19] Added by: R.Zacche - END -->
        </table>
    </div>
	<br>
    <button id="btnGerarPDF" type="submit" class="btn btn-primary" hidden>Gerar PDF</button>
	<span id="msgAvisoGerarPDF" class="alert alert-primary">Selecione um produto para liberar a consulta</span>
</form>

<br/>

<p><small>Explicar sobre o relatório.</small></p>

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script type="text/javascript" src="{{ STATIC_URL }}admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/zepto.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.mask.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/relatorio-contagem-estoque.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<!-- [08/08/19] Added by: R.Zacche -->
<!-- AngularJS -->
<script type="text/javascript" src="{{STATIC_URL}}js/angularjs/angular_1.5.8.min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/angularjs/angular-locale_pt-br.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/angularjs/app.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/angularjs/funcoes.js"></script>
<script type="text/javascript">
$("#produto_pk").val('');
$("#btnGerarPDF").hide();
$("#msgAvisoGerarPDF").show();
app.controller("ctrlContagemEstoqueRotativo", function( $scope, $http, Funcao ){
	// Localiza e retorna o produto com texto de busca --------
    $scope.buscarProduto = function(){

		$("#produto_pk").val('');
		$("#btnGerarPDF").hide();
		$("#msgAvisoGerarPDF").show();
        var textoBusca = $('#textoBusca').val();

        //$scope.estoqueDiario.data != undefined && 
        if ( textoBusca != undefined && textoBusca.length > 1 && textoBusca != '' ){
            // Faz busca do produto informado

            cliente_pk = $('#id_cliente').val();
            //data = Funcao.converteDateStringFormat($scope.estoqueDiario.data);

            var url = '/produtos/buscar-produto-estoque/';

            var fd = new FormData();
            fd.append('cliente_pk' , cliente_pk);
            fd.append('textoBusca' , textoBusca);
    
            $http.post(url, fd, {
                transformRequest: angular.identity,
                headers: {'Content-Type': undefined}
            })
            .then( 
                function(response){

                    if( response.data.res == 'no' ){
                        alert('O produto não foi localizado. Tente novamente!');
                    };

					$scope.produtos = [];
                    if ( response.data.res == 'ok'){
                        if ( response.data.quant > 1 ){
							$scope.produtos = response.data.lista_produtos;
                        }else{
							response.data.produto.label = response.data.produto.codigo_interno+' - '+response.data.produto.codigo_barras+' - '+response.data.produto.descricao;
							$scope.produtos.push(response.data.produto);
							//$("#produto_pk").val(response.data.produto.pk);
							//$("#btnGerarPDF").show();
							//$("#msgAvisoGerarPDF").hide();
							//$("input[name=prod]")[0].prop("checked",false);
                        };
                    }
                }
            );
        } else {
            $('#produto').focus()
        };
    }
	
	$scope.selecionarProduto = function(){
		$("#produto_pk").val($(this)[0].prod.pk);
		$("#btnGerarPDF").show();
		$("#msgAvisoGerarPDF").hide();
	}
});
</script>
{% endblock %}

produtos/templates/deletar-importar-planilha.html
{% extends "admin/base_site.html" %}

{% block extrastyle %}{{block.super}}
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/styles.css" %}" />
{% endblock extrastyle %}

{% block content %}
<h1>Importação <small>Planilha de Estoque Diário</small></h1>

<p class="texto_fosco">Explicar que a planilha tem que ser de um padrão e ter um link pra mostrar uma planilha modelo.</p>

<form method="POST" enctype="multipart/form-data">{% csrf_token %}
    <div class="inner">
        <table class="form">
            {{form}}
        </table>
    </div>
    <button type="submit">Importar</button>
</form>


<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script type="text/javascript" src="{{ STATIC_URL }}admin/js/vendor/jquery/jquery.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/zepto.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.mask.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/importar-planilha-estoque.js"></script>
{% endblock %}

produtos/templates/importar-planilha-estoque-diario.html
{% extends "admin/base_site.html" %}

{% block extrastyle %}{{block.super}}
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}css/styles.css" %}" />
{% endblock extrastyle %}

{% block content %}
<h1>Importação <small>Planilha de Estoque Diário</small></h1>

<form method="POST" enctype="multipart/form-data">{% csrf_token %}
    <div class="inner">
        <table class="form">
            {{form}}
        </table>
    </div>
    <button type="submit">Enviar arquivo</button>
</form>

<p class="texto_fosco">Explicar que a planilha tem que ser de um padrão e ter um link pra mostrar uma planilha modelo.</p>


<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script type="text/javascript" src="{{ STATIC_URL }}admin/js/vendor/jquery/jquery.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/zepto.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.mask.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/importar-planilha-estoque.js"></script>
{% endblock %}